[package]
name = "vastrum-git-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
gix-hash =  "0.22.1"
gix-object =  "0.57.0"
gix-actor =  "0.40.0"
gix-date =  "0.15.0"
vastrum-ts-macros.workspace = true
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
vastrum-shared-types = { version = "0.1.0", path = "../../../shared-types" }
vastrum-abi = { version = "0.1.0", path = "../../../runtime/vastrum-abi" }
vastrum-rpc-client = { version = "0.1.0", path = "../../../tooling/rpc-client" }
gitter-abi = { path = "../abi" }
futures = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
vastrum-native-lib = { version = "0.1.0", path = "../../../tooling/native-lib", features = ["localnet"] }
gix = { version ="0.80.0", default-features = false, features = ["parallel", "worktree-mutation", "index"] }
tokio = { version = "1.49.0", features = ["full", "tracing"] }
tempfile = "3"

[dev-dependencies]
gix = { version ="0.80.0", default-features = false, features = ["parallel", "worktree-mutation", "index"] }

