// This file is @generated by abi-codegen. Do not edit.

use std::sync::Arc;
pub use vastrum_abi::__private::vastrum_rpc_client::{RpcProvider, SentTxBehavior};
#[derive(Debug)]
pub struct NativeContract {
    pub admin: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
}
#[allow(dead_code)]
pub struct StateReader {
    client: Arc<vastrum_abi::__private::vastrum_rpc_client::RpcClient>,
}
impl StateReader {
    pub fn new(
        site_id: vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest,
    ) -> Self {
        Self {
            client: Arc::new(vastrum_abi::__private::vastrum_rpc_client::RpcClient::new(site_id)),
        }
    }
    pub fn from_client(client: Arc<vastrum_abi::__private::vastrum_rpc_client::RpcClient>) -> Self {
        Self { client }
    }
    #[allow(unused_parens)]
    pub async fn state(&self) -> NativeContract {
        let bytes = self.client.get_key_value("__state".to_string()).await.unwrap();
        let client = self.client.clone();
        let (f0): (vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey) =
            vastrum_abi::__private::vastrum_native_types::with_deser_client(&client, || {
                vastrum_abi::__private::borsh::from_slice(&bytes).unwrap()
            });
        NativeContract { admin: f0 }
    }
}
pub struct ContractAbiClient {
    client: vastrum_abi::__private::vastrum_rpc_client::RpcClient,
}
impl ContractAbiClient {
    pub fn new(
        site_id: vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest,
    ) -> Self {
        Self { client: vastrum_abi::__private::vastrum_rpc_client::RpcClient::new(site_id) }
    }
    pub fn site_id(
        &self,
    ) -> vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest {
        use vastrum_abi::__private::vastrum_rpc_client::RpcProvider;
        self.client.site_id()
    }
    pub fn with_account_key(
        self,
        key: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PrivateKey,
    ) -> Self {
        Self { client: self.client.with_account_key(key) }
    }
    #[doc = r" Returns the contract state"]
    pub async fn state(&self) -> NativeContract {
        StateReader::from_client(Arc::new(self.client.clone())).state().await
    }
    #[doc = r" Deploys contract, will only return when contract has actually been deployed and polls for inclusion"]
    #[doc = r" Can take some time for this function to return because of this"]
    #[cfg(not(target_arch = "wasm32"))]
    pub async fn deploy(
        wasm_path: &str,
        brotli_html_content: Vec<u8>,
        admin: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
    ) -> Self {
        let constructor_calldata =
            vastrum_abi::__private::borsh::to_vec(&(brotli_html_content, admin)).unwrap();
        let site_id = vastrum_abi::__private::vastrum_native_lib::deployers::deploy::deploy_module(
            wasm_path,
            constructor_calldata,
        )
        .await;
        vastrum_abi::__private::vastrum_native_lib::deployers::deploy::poll_until_site_id_deployed(
            site_id,
        )
        .await;
        Self::new(site_id)
    }
    pub async fn set_page(
        &self,
        brotli_html_content: Vec<u8>,
    ) -> vastrum_abi::__private::vastrum_rpc_client::SentTx {
        let mut calldata = vec![165u8, 3u8, 178u8, 54u8, 9u8, 44u8, 231u8, 229u8];
        calldata.extend(vastrum_abi::__private::borsh::to_vec(&(brotli_html_content)).unwrap());
        self.client.make_authenticated_call(calldata).await
    }
}
