// This file is @generated by abi-codegen. Do not edit.

use std::sync::Arc;
pub use vastrum_abi::__private::vastrum_rpc_client::{RpcProvider, SentTxBehavior};
#[derive(
    vastrum_abi :: __private :: borsh :: BorshSerialize,
    vastrum_abi :: __private :: borsh :: BorshDeserialize,
    Clone,
    Debug,
    Default,
)]
#[borsh(crate = "vastrum_abi::__private::borsh")]
pub struct TileCoord {
    pub z: u8,
    pub x: u32,
    pub y: u32,
}
#[derive(
    vastrum_abi :: __private :: borsh :: BorshSerialize,
    vastrum_abi :: __private :: borsh :: BorshDeserialize,
    Clone,
    Debug,
    Default,
)]
#[borsh(crate = "vastrum_abi::__private::borsh")]
pub struct MapMetadata {
    pub min_zoom: u8,
    pub max_zoom: u8,
    pub center_lat: i64,
    pub center_lng: i64,
    pub bounds_min_lat: i64,
    pub bounds_min_lng: i64,
    pub bounds_max_lat: i64,
    pub bounds_max_lng: i64,
}
#[derive(Debug)]
pub struct NativeContract {
    pub tiles: vastrum_abi::__private::vastrum_native_types::KvMap<TileCoord, Vec<u8>>,
    pub metadata: MapMetadata,
    pub admin: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
}
#[allow(dead_code)]
pub struct StateReader {
    client: Arc<vastrum_abi::__private::vastrum_rpc_client::RpcClient>,
}
impl StateReader {
    pub fn new(
        site_id: vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest,
    ) -> Self {
        Self {
            client: Arc::new(vastrum_abi::__private::vastrum_rpc_client::RpcClient::new(site_id)),
        }
    }
    pub fn from_client(client: Arc<vastrum_abi::__private::vastrum_rpc_client::RpcClient>) -> Self {
        Self { client }
    }
    #[allow(unused_parens)]
    pub async fn state(&self) -> NativeContract {
        let bytes = self.client.get_key_value("__state".to_string()).await.unwrap();
        let client = self.client.clone();
        let (f0, f1, f2): (
            u64,
            MapMetadata,
            vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
        ) = vastrum_abi::__private::vastrum_native_types::with_deser_client(&client, || {
            vastrum_abi::__private::borsh::from_slice(&bytes).unwrap()
        });
        NativeContract {
            tiles: vastrum_abi::__private::vastrum_native_types::KvMap::<TileCoord, Vec<u8>>::new(
                f0,
                client.clone(),
            ),
            metadata: f1,
            admin: f2,
        }
    }
}
pub struct ContractAbiClient {
    client: vastrum_abi::__private::vastrum_rpc_client::RpcClient,
}
impl ContractAbiClient {
    pub fn new(
        site_id: vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest,
    ) -> Self {
        Self { client: vastrum_abi::__private::vastrum_rpc_client::RpcClient::new(site_id) }
    }
    pub fn site_id(
        &self,
    ) -> vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest {
        use vastrum_abi::__private::vastrum_rpc_client::RpcProvider;
        self.client.site_id()
    }
    pub fn with_account_key(
        self,
        key: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PrivateKey,
    ) -> Self {
        Self { client: self.client.with_account_key(key) }
    }
    #[doc = r" Returns the contract state"]
    pub async fn state(&self) -> NativeContract {
        StateReader::from_client(Arc::new(self.client.clone())).state().await
    }
    #[doc = r" Deploys contract, will only return when contract has actually been deployed and polls for inclusion"]
    #[doc = r" Can take some time for this function to return because of this"]
    #[cfg(not(target_arch = "wasm32"))]
    pub async fn deploy(
        wasm_path: &str,
        brotli_html_content: Vec<u8>,
        admin: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
    ) -> Self {
        let constructor_calldata =
            vastrum_abi::__private::borsh::to_vec(&(brotli_html_content, admin)).unwrap();
        let site_id = vastrum_abi::__private::vastrum_native_lib::deployers::deploy::deploy_module(
            wasm_path,
            constructor_calldata,
        )
        .await;
        vastrum_abi::__private::vastrum_native_lib::deployers::deploy::poll_until_site_id_deployed(
            site_id,
        )
        .await;
        Self::new(site_id)
    }
    pub async fn upload_tile(
        &self,
        coord: TileCoord,
        data: Vec<u8>,
    ) -> vastrum_abi::__private::vastrum_rpc_client::SentTx {
        let mut calldata = vec![78u8, 41u8, 233u8, 202u8, 162u8, 116u8, 55u8, 195u8];
        calldata.extend(vastrum_abi::__private::borsh::to_vec(&(coord, data)).unwrap());
        self.client.make_authenticated_call(calldata).await
    }
    pub async fn upload_tiles(
        &self,
        tiles: Vec<(TileCoord, Vec<u8>)>,
    ) -> vastrum_abi::__private::vastrum_rpc_client::SentTx {
        let mut calldata = vec![238u8, 163u8, 148u8, 47u8, 39u8, 84u8, 142u8, 92u8];
        calldata.extend(vastrum_abi::__private::borsh::to_vec(&(tiles)).unwrap());
        self.client.make_authenticated_call(calldata).await
    }
    pub async fn set_metadata(
        &self,
        metadata: MapMetadata,
    ) -> vastrum_abi::__private::vastrum_rpc_client::SentTx {
        let mut calldata = vec![61u8, 89u8, 175u8, 25u8, 178u8, 94u8, 253u8, 223u8];
        calldata.extend(vastrum_abi::__private::borsh::to_vec(&(metadata)).unwrap());
        self.client.make_authenticated_call(calldata).await
    }
}
