// This file is @generated by abi-codegen. Do not edit.

use std::sync::Arc;
pub use vastrum_abi::__private::vastrum_rpc_client::{RpcProvider, SentTxBehavior};
#[derive(
    vastrum_abi :: __private :: borsh :: BorshSerialize,
    vastrum_abi :: __private :: borsh :: BorshDeserialize,
    Clone,
    Debug,
    Default,
)]
#[borsh(crate = "vastrum_abi::__private::borsh")]
pub struct DocumentWriteOperation {
    pub content: Vec<u8>,
    pub metadata: Vec<u8>,
}
#[derive(Debug)]
pub struct NativeContract {
    pub user_data: vastrum_abi::__private::vastrum_native_types::KvMap<
        vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
        Vec<u8>,
    >,
    pub documents: vastrum_abi::__private::vastrum_native_types::KvMap<
        vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
        Vec<u8>,
    >,
    pub doc_metadata: vastrum_abi::__private::vastrum_native_types::KvMap<
        vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
        Vec<u8>,
    >,
}
#[allow(dead_code)]
pub struct StateReader {
    client: Arc<vastrum_abi::__private::vastrum_rpc_client::RpcClient>,
}
impl StateReader {
    pub fn new(
        site_id: vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest,
    ) -> Self {
        Self {
            client: Arc::new(vastrum_abi::__private::vastrum_rpc_client::RpcClient::new(site_id)),
        }
    }
    pub fn from_client(client: Arc<vastrum_abi::__private::vastrum_rpc_client::RpcClient>) -> Self {
        Self { client }
    }
    #[allow(unused_parens)]
    pub async fn state(&self) -> NativeContract {
        let bytes = self.client.get_key_value("__state".to_string()).await.unwrap();
        let client = self.client.clone();
        let (f0, f1, f2): (u64, u64, u64) =
            vastrum_abi::__private::vastrum_native_types::with_deser_client(&client, || {
                vastrum_abi::__private::borsh::from_slice(&bytes).unwrap()
            });
        NativeContract {
            user_data: vastrum_abi::__private::vastrum_native_types::KvMap::<
                vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
                Vec<u8>,
            >::new(f0, client.clone()),
            documents: vastrum_abi::__private::vastrum_native_types::KvMap::<
                vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
                Vec<u8>,
            >::new(f1, client.clone()),
            doc_metadata: vastrum_abi::__private::vastrum_native_types::KvMap::<
                vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
                Vec<u8>,
            >::new(f2, client.clone()),
        }
    }
}
pub struct ContractAbiClient {
    client: vastrum_abi::__private::vastrum_rpc_client::RpcClient,
}
impl ContractAbiClient {
    pub fn new(
        site_id: vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest,
    ) -> Self {
        Self { client: vastrum_abi::__private::vastrum_rpc_client::RpcClient::new(site_id) }
    }
    pub fn site_id(
        &self,
    ) -> vastrum_abi::__private::vastrum_shared_types::crypto::sha256::Sha256Digest {
        use vastrum_abi::__private::vastrum_rpc_client::RpcProvider;
        self.client.site_id()
    }
    pub fn with_account_key(
        self,
        key: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PrivateKey,
    ) -> Self {
        Self { client: self.client.with_account_key(key) }
    }
    #[doc = r" Returns the contract state"]
    pub async fn state(&self) -> NativeContract {
        StateReader::from_client(Arc::new(self.client.clone())).state().await
    }
    #[doc = r" Deploys contract, will only return when contract has actually been deployed and polls for inclusion"]
    #[doc = r" Can take some time for this function to return because of this"]
    #[cfg(not(target_arch = "wasm32"))]
    pub async fn deploy(wasm_path: &str, brotli_html_content: Vec<u8>) -> Self {
        let constructor_calldata =
            vastrum_abi::__private::borsh::to_vec(&(brotli_html_content,)).unwrap();
        let site_id = vastrum_abi::__private::vastrum_native_lib::deployers::deploy::deploy_module(
            wasm_path,
            constructor_calldata,
        )
        .await;
        vastrum_abi::__private::vastrum_native_lib::deployers::deploy::poll_until_site_id_deployed(
            site_id,
        )
        .await;
        Self::new(site_id)
    }
    pub async fn save_user_data(
        &self,
        data: Vec<u8>,
    ) -> vastrum_abi::__private::vastrum_rpc_client::SentTx {
        let mut calldata = vec![90u8, 215u8, 61u8, 92u8, 160u8, 242u8, 96u8, 38u8];
        calldata.extend(vastrum_abi::__private::borsh::to_vec(&(data)).unwrap());
        self.client.make_authenticated_call(calldata).await
    }
    pub async fn save_document(
        &self,
        document_key: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::PublicKey,
        signature: vastrum_abi::__private::vastrum_shared_types::crypto::ed25519::Signature,
        operation: DocumentWriteOperation,
    ) -> vastrum_abi::__private::vastrum_rpc_client::SentTx {
        let mut calldata = vec![216u8, 252u8, 95u8, 228u8, 142u8, 249u8, 166u8, 152u8];
        calldata.extend(
            vastrum_abi::__private::borsh::to_vec(&(document_key, signature, operation)).unwrap(),
        );
        self.client.make_authenticated_call(calldata).await
    }
}
