[package]
name = "mapper-tile-uploader"
version = "0.1.0"
edition = "2024"

[dependencies]
mapper-abi = { path = "../abi" }
vastrum-rpc-client = { version = "0.1.0", path = "../../../tooling/rpc-client" }
vastrum-shared-types = { version = "0.1.0", path = "../../../shared-types" }
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.34", features = ["bundled"] }
sha2 = "0.10"
osmpbf = "0.3"
geozero = { version = "0.15.1", default-features = false, features = ["with-mvt"] }

